### ISSUE TITLE
A description might be wrong.

### ISSUE THREAD

**Issue by serious-angel** [noamyogev84/ConcurrentPriorityQueue#2]
Dear Developer,

Please check these words inside a description of this project: `A thread-safe generic first in first out (FIFO) collection with support for priority queuing.` - this might be wrong.

> FIFO: It is analogous to processing a queue with first-come, first-served (FCFS) behaviour: where the people leave the queue in the order in which they arrive. [source](https://en.wikipedia.org/wiki/FIFO_(computing_and_electronics))

In other words: FIFO is strictly FIFO, priority would mess this at some moment, wouldn't it?

**Comment by noamyogev84** [comment]
Thanks for this feedback @F8ER 
Any thought on how it should be described?
