### ISSUE TITLE
Blocking Collection throws Exception if Queue is bound

### ISSUE THREAD

**Issue by rj2Skipper** [noamyogev84/ConcurrentPriorityQueue#3]
Hey Noam,
i appreciate this work you've done.
I'am in the process of replacing my plain BlockingCollection usage with this Priority based Queue but do need the threadsafe and blocking capabilities 

I came across an issue I can't solve by myself: If PriorityQueue is initialzed with bounds (e.g. 2) enqueuing a 3rd item fails as expected.
But adding a 3rd Item to the "derived" BlockingCollection throws Exception, and does not wait until there is space in collection again, as would be the behavior for BlockingCollection.

code to reproduce:
```
void Test_BoundBlockingCollection()
        {
            var q = new ConcurrentPriorityQueue.ConcurrentPriorityByIntegerQueue<MockWithIntegerPriority>(2);
            for (int i = 0; i < 4; i++)
            {
                q.TryAdd(new MockWithIntegerPriority(i));
                // result: 2 x ok, 2 x fail
            }

            var q2 = new ConcurrentPriorityQueue.ConcurrentPriorityByIntegerQueue<MockWithIntegerPriority>(2);
            var b = q2.ToBlockingCollection();
            for (int i = 0; i < 4; i++)
            {
                b.Add(new MockWithIntegerPriority(i));
                //result: 2 x ok, then System.InvalidOperationException: 'The underlying collection didn't accept the item.'
            }
        }
```

can you help with that issue?

caio Ralf

**Comment by noamyogev84** [comment]
Hey @rj2Skipper.
So sorry that i'm seeing your comment just now.
I will look into it, if you have a PR ready for it i would love to merge it.

THX 🎉

**Comment by rj2Skipper** [comment]
Hi @noamyogev84 
please take a look at PR#4 
it's allready marked closed !?

Ralf

**Comment by noamyogev84** [comment]
Hey @rj2Skipper it looks like you're feature branch was removed and the PR closed due to that.
Go ahead and open a new PR

**Comment by noamyogev84** [comment]
Going to close that one.
Thanks @rj2Skipper 🙏
