### ISSUE TITLE
Add stylecop analyzers and a ruleset to solution

### ISSUE THREAD

**Issue by noamyogev84** [noamyogev84/ConcurrentPriorityQueue#6]
Add some basic coding rules and styles
enforce by adding analyzers and enforce by build

**Comment by damiansikora85** [comment]
Hi, I could take a look at this, please assign me ;)

**Comment by noamyogev84** [comment]
Hey @damiansikora85 thanks for your comment.
This issues is resolved, I actually had some time to play with it.

Feel free to take anything else from the open issues
