### ISSUE TITLE
Fix Link in documentation for IProdcerConsumerCollection

### ISSUE THREAD

**Issue by noamyogev84** [noamyogev84/ConcurrentPriorityQueue#8]
link is broken
need to link to Microsoft documentation

**Comment by DelayCoderz** [comment]
assign me @noamyogev84

**Comment by DelayCoderz** [comment]
@noamyogev84 i finished solve this issue , please review my pull request :)

**Comment by noamyogev84** [comment]
Thanks for you work @DelayCoderz 🐱‍🏍

**Comment by DelayCoderz** [comment]
:D
